title: Apache Cayenne
email: amaniatis@apache.org
description: >
  Apache Cayenne(tm) is an open source persistence framework licensed
  under the Apache License, providing object-relational mapping (ORM) and 
  remoting services. With a wealth of unique and powerful features, 
  Cayenne can address a wide range of persistence needs. Cayenne seamlessly 
  binds one or more database schemas directly to Java objects, managing atomic 
  commit and rollbacks, SQL generation, joins, sequences, and more. With Cayenne's
  Remote Object Persistence, those Java objects can even be persisted out to 
  clients via Web Services.
baseurl: ""
url: "http://cayenne.apache.org"
encoding: utf-8

# Build settings

# theme: minima
gems:
#  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

markdown: kramdown
kramdown:
  auto_ids: true # Auto-generate ID's for headings

sass:
  style: compressed
  sass_dir: assets/css/_sass

defaults:
  -
    scope:
      path: "assets" # an empty string here means all files in the project
    values:
      layout:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"